# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6648fb4dad1c634d192016957f0e1b495745ce3cfbad34192190ead8750fc0e959cfd6f85c767feaf383d307be5217b2dc5456fe0bbe50d6c7fb55e8cd8eaf2f

test:
  secret_key_base: 0d1d5506a24f5f515d7f2cfbf0f42415901e5a90ddd19e5c8b0ba75985589a544b71d91af93319670a6541359ba743937feb80c872c593ed38a858515f13a926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
